name: Build extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install extension dependencies
      run: npm ci

    - name: Package the extension
      run: npx -p @vscode/vsce -c 'vsce package'
